/**
 * BidLua - compiled language for Lua.
 * Copyright (C) 2023 defaultzon3
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see < https://www.gnu.org/licenses/ >.
 */

package names

var names : Map<String, String> = mapOf(
    // Default Lua names.getNames.
    "иче"                   to "and",
    "и"                     to "and",
    "ыыы"                   to "and",
    "вальнисьнах"           to "break",
    "закройся"              to "break",
    "пиздуй"                to "break",
    "паши"                  to "do",
    "делай"                 to "do",
    "вася"                  to "do",
    "гнида"                 to "do",
    "лох"                   to "do",
    "паскуда"               to "do",
    "или"                   to "else",
    "чо"                    to "else",
    "чооо"                  to "else",
    "нухули"                to "else",
    "иличе"                 to "elseif",
    "этоЧЕ??"               to "elseif",
    "блянухули"             to "elseif",
    "елсеиф"                to "elseif",
    "всеепт"                to "end",
    "чмо"                   to "end",
    "гыы"                   to "end",
    "буээ"                  to "end",
    "бывайтенах"            to "end",
    "досвязи"               to "end",
    "всеёпт"                to "end",
    "пиздишь"               to "false",
    "нечетко"               to "false",
    "пиздеж"                to "false",
    "даун"                  to "false",
    "лооожь"                to "false",
    "неебу"                 to "goto",
    "прыгни"                to "goto",
    "передтобойдвастула"    to "goto",
    "бляэто"                to "goto",
    "пидор"                 to "goto",
    "ля"                    to "for",
    "длялоха"               to "for",
    "подшконочный"          to "for",
    "бубна"                 to "for",
    "легенда"               to "for",
    "длябля"                to "for",
    "делай"                 to "for",
    "рабочий"               to "function",
    "работяга"              to "function",
    "обана"                 to "function",
    "эточематематика?"      to "function",
    "фунфункция"            to "function",
    "мумия"                 to "function",
    "терпила"               to "function",
    "гей"                   to "function",
    "натурал"               to "function",
    "еслиты"                to "if",
    "если"                  to "if",
    "хуиф"                  to "if",
    "мужык"                 to "if",
    "анубля"                to "if",
    "идинахуй"              to "if",
    "нусука"                to "if",
    "шобы"                  to "if",
    "нуэто"                 to "if",
    "валера"                to "if",
    "глянь"                 to "if",
    "епт"                   to "if",
    "падем"                 to "if",
    "услович"               to "if",
    "внутривенно"           to "in",
    "анукабля"              to "in",
    "чевкарманах"           to "in",
    "этоинн??"              to "in",
    "внутричмо"             to "in",
    "давайбля"              to "in",
    "участковый"            to "local",
    "эй"                    to "local",
    "ты"                    to "local",
    "эйтыбля"               to "local",
    "веленотебе"            to "local",
    "петух"                 to "local",
    "опущенный"             to "local",
    "бурда"                 to "local",
    "нолик"                 to "nil",
    "полныйноль"            to "nil",
    "нулевой"               to "nil",
    "ебатьтыноль"           to "nil",
    "нилхуил"               to "nil",
    "естьрекатакая"         to "nil",
    "билхуил"               to "nil",
    "хуил"                  to "nil",
    "нотнот"                to "not",
    "ойсорянбрат"           to "not",
    "хует"                  to "not",
    "нетминет"              to "not",
    "пидораответ"           to "not",
    "шлюхиаргумент"         to "not",
    "иначече"               to "or",
    "иличе"                 to "or",
    "илитыпетух"            to "or",
    "жиес"                  to "or",
    "илиЧО"                 to "or",
    "нах"                   to "or",
    "ору"                   to "or",
    "повторика"             to "repeat",
    "четысказалтам?"        to "repeat",
    "репитбля"              to "repeat",
    "леее"                  to "repeat",
    "четысказал"            to "repeat",
    "повторись"             to "repeat",
    "вернись"               to "return",
    "верника"               to "return",
    "долгвернешь"           to "return",
    "повернисьбля"          to "return",
    "вернисука"             to "return",
    "тогдаче"               to "then",
    "дзен??ченах"           to "then",
    "тогдатылохи"           to "then",
    "потомкороче"           to "then",
    "тхрен"                 to "then",
    "хуен"                  to "then",
    "ёпт"                   to "then",
    "епт"                   to "then",
    "похвалиепт"            to "then",
    "похвалиёпт"            to "then",
    "истинный"              to "true",
    "ноликилиединица??"     to "true",
    "трушныйпацан"          to "true",
    "верныйчел"             to "true",
    "четко"                 to "true",
    "охуважаю!!"            to "true",
    "покачмо"               to "until",
    "хуептил"               to "until",
    "вертил"                to "until",
    "унтилахах"             to "until",
    "цикльный"              to "while",
    "зацикленныйдаун"       to "while",
    "повторяющийсячмо"      to "while",
    "повторюшка"            to "while",
    "тынеповторяйсянукабля" to "while",
    "вайлхуяйлбля!"         to "while",

    // Lua comparison operators.
    "опущенее"              to "<",
    "лох?"                  to "<",
    "ниженка"               to "<",
    "блатнее"               to ">",
    "выше"                  to ">",
    "блатной?"              to ">",
    "опущенкажыесть"        to "<=",
    "полныйдауннах?"        to "<=",
    "полнейшийлохбля!"      to "<=",
    "блатнойбратуха"        to ">=",
    "вышеменядажебля"       to ">=",
    "блатнойбля!!!"         to ">=",
    "жыесть"                to "==",
    "жынах"                 to "==",
    "хулион"                to "==",
    "жынет"                 to "~=",
    "жыненахбля"            to "~=",
    "ненаш??"               to "~=",

    // Lua assignment operator.
    "будет"                 to "=",
    "быть"                  to "=",
    "жы"                    to "=",

    // Lua arithmetic operators.
    "сложисука"             to "+",
    "барашик"               to "+",
    "баклан"                to "-",
    "басило"                to "-",
    "умнож"                 to "*",
    "умножбля"              to "*",
    "делила"                to "/",
    "делинах"               to "/",
    "крошки"                to "%",
    "заотсталь"             to "%",
    "сухарь"                to "^",
    "степь"                 to "^",

    // Lua default functions.
    "морозишь"              to "assert",
    "заяви"                 to "assert",
    "вынесимусор"           to "collectgarbage",
    "коллектормусора"       to "collectgarbage",
    "духаст"                to "dofile",
    "выполнисука"           to "dofile",
    "ошибкамолодости"       to "error",
    "успех"                 to "error",
    "глобал"                to "_G",
    "получипоебалу"         to "getmetatable",
    "главныйлох"            to "ipairs",
    "грузчик"               to "load",
    "грузчикговна"          to "loadfile",
    "следующийёпт"          to "next",
    "меньшийлох"            to "pairs",
    "позвони"               to "pcall",
    "перезвони"             to "pcall",
    "убогий"                to "print",
    "говножуй"              to "print",
    "хуйжопа"               to "print",
    "грррааеквал"           to "rawequal",
    "грраавсет"             to "rawset",
    "должник"               to "require",
    "вкабале"               to "require",
    "кабал"                 to "require",
    "балана"                to "select",
    "поставьебало"          to "setmetatable",
    "цыфра"                 to "tonumber",
    "вциферки"              to "tonumber",
    "впропись"              to "tostring",
    "вжопу"                 to "tostring",
    "типа"                  to "type",
    "типочек"               to "type",
    "распаковщик"           to "unpack",
    "звонокпрокурору"       to "xpcall",
    "главный"               to "_VERSION",
    "накажи"                to "warn",

    // Lua default coroutine library functions.
    "конецкороны"           to "coroutine.close",
    "короваклоуз"           to "coroutine.close",
    "короновирусёпт"        to "coroutine.open",
    "китайцыбля"            to "coroutine.open",
    "чтоэтотакое"           to "coroutine.isyieldable",
    "продолжайсосать"       to "coroutine.resume",
    "статусназоне"          to "coroutine.running",
    "статусзоны"            to "coroutine.status",
    "врапхуяпк"             to "coroutine.wrap",
    "зараженноеполенах"     to "coroutine.yield",

    // Lua default string library functions.
    "писарь"                to "string",
    "ксива"                 to "string",
    "писарь0101"            to "string.bit",
    "програмист0101"        to "bit",
    "писарьнулевой"         to "string.char",
    "программистнулевой"    to "char",
    "писарьдаун0101"        to "string.dump",
    "дамб"                  to "dump",
    "поискпоайпи"           to "string.find",
    "ультрапоискпоайпи"     to "find",
    "вычислиайпи"           to "find",
    "форматсука"            to "string.format",
    "гыыформат"             to "format",
    "поискшкольников"       to "string.gmatch",
    "ищишкольников"         to "gmatch",
    "пиздилохов"            to "string.gsub",
    "ебашьлохов"            to "gsub",
    "скокчлен"              to "string.len",
    "длиначлена"            to "len",
    "вниз"                  to "string.lower",
    "внизнах"               to "lower",
    "антилопа"              to "string.match",
    "матч"                  to "match",
    "курьернах"             to "string.pack",
    "курьер"                to "pack",
    "повторила"             to "string.rep",
    "повторибля"            to "rep",
    "повернись"             to "string.reverse",
    "поверни"               to "reverse",
    "собвей"                to "string.sub",
    "сабвей"                to "sub",
    "полукурьернах"         to "string.unpack",
    "полукурьер"            to "unpack",
    "вверх"                 to "string.upper",
    "вверхнах"              to "upper",

    // Lua default UTF-8 library functions.
    "утф8"                  to "utf8",
    "полотно"               to "charpattern",
    "пароли"                to "codes",
    "точкапаролянах"        to "codepoint",
    "длина"                 to "len",
    "майндсет"              to "offset",

    // Lua default table library functions.
    "бадяга"                to "table",
    "варежка"               to "table",
    "валежник"              to "unpack",
    "верти"                 to "insert",
    "верха"                 to "insert",
    "весло"                 to "insert",
    "обьединяло"            to "concat",
    "кокатбля"              to "concat",
    "пиздуй"                to "move",
    "псевдовалежник"        to "pack",
    "сортировщик"           to "sort",

    // Lua default mathematical functions.
    "гопник"                to "math",
    "математик"             to "math",
    "козенный"              to "math",
    "абсолютный"            to "abs",
    "акос"                  to "acos",
    "асинусин"              to "asin",
    "атанинус"              to "atan",
    "клетка"                to "ceil",
    "синусискосинус"        to "cos",
    "дег"                   to "deg",
    "опыт"                  to "exp",
    "пол"                   to "floor",
    "круглый"               to "floor",
    "фунах"                 to "fmod",
    "хуйхуеге"              to "huge",
    "максос"                to "maxinteger",
    "минсос"                to "mininteger",
    "изменчивый"            to "modf",
    "ПИЗДА"                 to "pi",
    "пи"                    to "pi",
    "пизда"                 to "pi",
    "маслина"               to "rad",
    "рандомный"             to "random",
    "нихуянерандомный"      to "randomseed",
    "синус"                 to "sin",
    "квадрат"               to "sqrt",
    "тянка"                 to "tan",
    "вчлен"                 to "tointeger",
    "типцифры?чебля"        to "type",
    "ебаниульту"            to "ult",

    // Lua default input and output library.
    "висп"                  to "io",
    "иаиа"                  to "io",
    "ныаа"                  to "io",
    "закрылебало"           to "close",
    "энергетик"             to "flush",
    "приемный"              to "input",
    "линейноечмо"           to "lines",
    "откройебало"           to "open",
    "открылебало"           to "open",
    "выведимаму"            to "output",
    "поткройебало"          to "popen",
    "умник"                 to "read",
    "очкарик"               to "read",
    "тмппокмс"              to "tmpfile",
    "писарьнах"             to "write",
    "пишисука"              to "write",
    "пишибля"               to "write",
    "пиши"                  to "write",

    // Lua default operating system library.
    "винда"                 to "os",
    "линукс"                to "os", // yadro
    "ось"                   to "os",
    "немцы"                 to "os",
    "часы"                  to "clock",
    "часовой"               to "clock",
    "календарьёпт"          to "date",
    "вчемразницасука"       to "difftime",
    "дивайн"                to "difftime",
    "выполнигенийбля"       to "execute",
    "даунчмо"               to "execute",
    "говно"                 to "execute",
    "выйди"                 to "exit",
    "выйдиизайдинормально"  to "exit",
    "получипоебалу"         to "getenv",
    "удалисука"             to "remove",
    "переменуйсука"         to "rename",
    "поставьсука"           to "setlocale",
    "скольковремяща"        to "time",
    "скоквремя"             to "time",
    "времмммидинахуй"       to "tmpname"
)