/**
 * BidLua - compiled language for Lua.
 * Copyright (C) 2023 defaultzon3 (also known as DZONE)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see < https://www.gnu.org/licenses/ >.
 */

package names

var names : Map<String, String> = mapOf(
    // Default Lua names.getNames.
    "иче"                   to "and",
    "и"                     to "and",
    "ыыы"                   to "and",
    "вальнисьнах"           to "break",
    "закройся"              to "break",
    "пиздуй"                to "break",
    "паши"                  to "do",
    "делай"                 to "do",
    "вася"                  to "do",
    "гнида"                 to "do",
    "лох"                   to "do",
    "паскуда"               to "do",
    "или"                   to "else",
    "чо"                    to "else",
    "чооо"                  to "else",
    "нухули"                to "else",
    "иличе"                 to "elseif",
    "этоЧЕ??"               to "elseif",
    "блянухули"             to "elseif",
    "елсеиф"                to "elseif",
    "всеепт"                to "end",
    "чмо"                   to "end",
    "гыы"                   to "end",
    "буээ"                  to "end",
    "бывайтенах"            to "end",
    "досвязи"               to "end",
    "всеёпт"                to "end",
    "пиздишь"               to "false",
    "нечетко"               to "false",
    "пиздеж"                to "false",
    "даун"                  to "false",
    "лооожь"                to "false",
    "неебу"                 to "goto",
    "прыгни"                to "goto",
    "передтобойдвастула"    to "goto",
    "бляэто"                to "goto",
    "пидор"                 to "goto",
    "ля"                    to "for",
    "длялоха"               to "for",
    "подшконочный"          to "for",
    "бубна"                 to "for",
    "легенда"               to "for",
    "длябля"                to "for",
    "делай"                 to "for",
    "рабочий"               to "function",
    "работяга"              to "function",
    "обана"                 to "function",
    "эточематематика?"      to "function",
    "фунфункция"            to "function",
    "мумия"                 to "function",
    "терпила"               to "function",
    "гей"                   to "function",
    "натурал"               to "function",
    "еслиты"                to "if",
    "если"                  to "if",
    "хуиф"                  to "if",
    "мужык"                 to "if",
    "анубля"                to "if",
    "идинахуй"              to "if",
    "нусука"                to "if",
    "шобы"                  to "if",
    "нуэто"                 to "if",
    "валера"                to "if",
    "глянь"                 to "if",
    "епт"                   to "if",
    "падем"                 to "if",
    "услович"               to "if",
    "внутривенно"           to "in",
    "анукабля"              to "in",
    "чевкарманах"           to "in",
    "этоинн??"              to "in",
    "внутричмо"             to "in",
    "давайбля"              to "in",
    "участковый"            to "local",
    "эй"                    to "local",
    "ты"                    to "local",
    "эйтыбля"               to "local",
    "веленотебе"            to "local",
    "петух"                 to "local",
    "опущенный"             to "local",
    "бурда"                 to "local",
    "нолик"                 to "nil",
    "полныйноль"            to "nil",
    "нулевой"               to "nil",
    "ебатьтыноль"           to "nil",
    "нилхуил"               to "nil",
    "естьрекатакая"         to "nil",
    "билхуил"               to "nil",
    "хуил"                  to "nil",
    "нотнот"                to "not",
    "ойсорянбрат"           to "not",
    "хует"                  to "not",
    "нетминет"              to "not",
    "пидораответ"           to "not",
    "шлюхиаргумент"         to "not",
    "иначече"               to "or",
    "иличе"                 to "or",
    "илитыпетух"            to "or",
    "жиес"                  to "or",
    "илиЧО"                 to "or",
    "нах"                   to "or",
    "ору"                   to "or",
    "повторика"             to "repeat",
    "четысказалтам?"        to "repeat",
    "репитбля"              to "repeat",
    "леее"                  to "repeat",
    "четысказал"            to "repeat",
    "повторись"             to "repeat",
    "вернись"               to "return",
    "верника"               to "return",
    "долгвернешь"           to "return",
    "повернисьбля"          to "return",
    "вернисука"             to "return",
    "тогдаче"               to "then",
    "дзен??ченах"           to "then",
    "тогдатылохи"           to "then",
    "потомкороче"           to "then",
    "тхрен"                 to "then",
    "хуен"                  to "then",
    "ёпт"                   to "then",
    "епт"                   to "then",
    "похвалиепт"            to "then",
    "похвалиёпт"            to "then",
    "истинный"              to "true",
    "ноликилиединица??"     to "true",
    "трушныйпацан"          to "true",
    "верныйчел"             to "true",
    "четко"                 to "true",
    "охуважаю!!"            to "true",
    "покачмо"               to "until",
    "хуептил"               to "until",
    "вертил"                to "until",
    "унтилахах"             to "until",
    "цикльный"              to "while",
    "зацикленныйдаун"       to "while",
    "повторяющийсячмо"      to "while",
    "повторюшка"            to "while",
    "тынеповторяйсянукабля" to "while",
    "вайлхуяйлбля!"         to "while",

    // Lua comparison operators.
    "опущенее"              to "<",
    "лох?"                  to "<",
    "ниженка"               to "<",
    "блатнее"               to ">",
    "выше"                  to ">",
    "блатной?"              to ">",
    "опущенкажыесть"        to "<=",
    "полныйдауннах?"        to "<=",
    "полнейшийлохбля!"      to "<=",
    "блатнойбратуха"        to ">=",
    "вышеменядажебля"       to ">=",
    "блатнойбля!!!"         to ">=",
    "жыесть"                to "==",
    "жынах"                 to "==",
    "хулион"                to "==",
    "жынет"                 to "~=",
    "жыненахбля"            to "~=",
    "ненаш??"               to "~=",

    // Lua assignment operator.
    "будет"                 to "=",
    "быть"                  to "=",
    "жы"                    to "=",

    // Lua arithmetic operators.
    "сложисука"             to "+",
    "дваплюсдвасколькобля?" to "+",
    "сложиятечематематик"   to "+",
    "сложибляпобратски"     to "+"
)